name: JSON Validation

on:
  push:
  pull_request:

jobs:
  validate_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Validate JSON
        run: |
          python scripts/validate_json.py
